#!/usr/bin/env bash
# shell/direnv.sh — workbench-shell
# direnv configuration — shell hook integration. Registered at tier: tools
# (workbench.yml), sourced unconditionally — self-guards on
# `command -v direnv`. Shell-aware: uses direnv hook bash/zsh depending on
# WORKBENCH_SHELL.
#
# Config lives at ~/.config/direnv/direnv.toml (XDG default — direnv finds it
# automatically, no DIRENV_CONFIG export needed). Deployed by this module's
# files/direnv.toml (workbench.yml deploy[]), created once, never
# overwritten — see this repo's README for what it sets.

# ── Quieter output ────────────────────────────────────────────────────────
# Suppresses the "direnv: loading/unloading ..." lines on every cd.
# Per-call verbosity for debugging: DIRENV_LOG_FORMAT='direnv: %s' direnv reload
export DIRENV_LOG_FORMAT=""

# ── Shell hook ─────────────────────────────────────────────────────────────
case "${WORKBENCH_SHELL}" in
    bash|zsh)
        eval "$(direnv hook "${WORKBENCH_SHELL}")"
        ;;
    *)
        log_warn "direnv: unsupported shell '${WORKBENCH_SHELL}' — skipping hook"
        return 0
        ;;
esac

log_debug "direnv: hook installed (shell=${WORKBENCH_SHELL})"

# ── functions ────────────────────────────────────────────────────────────────

# Open the direnv config in $EDITOR.
edit-direnv-config() {
    local config_file="${XDG_CONFIG_HOME:-${HOME}/.config}/direnv/direnv.toml"
    "${EDITOR:-vi}" "${config_file}"
}

# direnv-init-project [path]
# Scaffold a starter .envrc in the given directory (default: cwd).
# Does not overwrite an existing .envrc — except that if the existing .envrc
# is one generated by workbench-git's CLI wiring (git-add-project-cli et al,
# identified by its first-line marker), it scaffolds .envrc.local instead,
# since that managed file is regenerated on every git-sync-projects and must
# not be hand-edited. See workbench-git's README.md#cli-context.
direnv-init-project() {
    local target_dir="${1:-.}"
    local envrc="${target_dir}/.envrc"

    if [[ -f "${envrc}" ]]; then
        # Matches on a stable prefix, not the full marker line — must stay
        # in sync with _GIT_ENVRC_MARKER_PREFIX in workbench-git's shell/git.sh.
        if head -n1 "${envrc}" 2>/dev/null | grep -qF '# Generated by workbench-git'; then
            local local_envrc="${target_dir}/.envrc.local"
            if [[ -f "${local_envrc}" ]]; then
                log_warn "${local_envrc} already exists — not overwriting"
                return 1
            fi

            cat > "${local_envrc}" <<'EOF'
# Local overrides for this project's direnv environment — never touched by
# workbench. Loaded by the generated .envrc via source_env_if_exists.
# See: https://direnv.net/man/direnv-stdlib.1.html

# Load a .env file alongside this .envrc, if present.
dotenv_if_exists

# Example: pin AWS/Azure context per project
# export AWS_PROFILE=myprofile
# export ARM_SUBSCRIPTION_ID=...

# Example: layout for Python venvs
# layout python3
EOF

            log_info "${envrc} is managed by workbench-git — created ${local_envrc} instead"
            echo "  It loads automatically; 'direnv allow' only if direnv hasn't seen this directory before."
            return 0
        fi

        log_warn "${envrc} already exists — not overwriting"
        return 1
    fi

    cat > "${envrc}" <<'EOF'
# direnv environment for this project.
# See: https://direnv.net/man/direnv-stdlib.1.html

# Load a .env file alongside this .envrc, if present.
dotenv_if_exists

# Example: pin AWS/Azure context per project
# export AWS_PROFILE=myprofile
# export ARM_SUBSCRIPTION_ID=...

# Example: layout for Python venvs
# layout python3
EOF

    log_info "Created ${envrc}"
    echo "  Run 'direnv allow' in ${target_dir} to activate it."
}
